import os

#Subreddit for Scraping
subred = "askreddit"

#Ignore Comments Having These Words
ignore = ["https://" , "http://" , "edit" , "EDIT" , "Edit" , "#" , "jpg" , "jpeg" , "png", "gif"]

#Characters for Comments
min = 10
max = 250

#Video Length (In Seconds)
comm_length = 30

#Voice for TTS
#Choose from -  Brian, Emma, Russell, Joey, Matthew, Joanna, Kimberly,
#               Amy, Geraint, Nicole, Justin, Ivy, Kendra, Salli, Raveena
tts_voice = "Matthew"

#Choose a Video for Background
video_list = ["minecraft1.mp4", 
              "minecraft2.mp4", 
              "hot_wheels.mp4", 
              "bike.mp4"]

#Customize Post Images
name        = ""
username    = ""
client      = "Twitter for iPhone" #Twitter for iPhone, Twitter for Android, Twitter Web App, etc.
profile_pic = os.getcwd()+"/assets/profile.png"
verified    = "show" #show, hide
theme       = "dim" #light, dim

#Caption for Instagram
insta_caption = ("")


#Data for Youtube Video Upload
emoji       = ["😀", "😁", "🧐", "🤓", "😇", "🥳", "🥺", "🤪", "😝", "😜", "😛", "🤩", "🥰", "😘", "😍", "😎", 
               "😋", "😊", "😉", "😆", "😅", "😄", "😃", "🤣", "😂", "😺", "🐱", "😼", "😹", "😸", "💖", "🌝"]

discription = ""
category    = "Entertainment"
tags        = ""

#Time To Wait for Uploading Youtube Video
#(Depending on the Video Size and Upload Speed)
upload_time = 200 #Seconds

#Time To Sleep Before Uploading Next Video
sleep_time = 5  #Hours









#Handles for Creating Comments
handles = {
    "Emma Jones": "emmajones",
    "John Smith": "johnsmith",
    "Megan Garcia": "megangarcia",
    "Avery Lee": "averylee",
    "Adam Brown": "adambrown",
    "Isabelle Martin": "isabellemartin",
    "Ethan Hill": "ethanhill",
    "Nora Lee": "noralee",
    "Landon Torres": "landontorres",
    "Emily Baker": "emilybaker",
    "Fizzy Pop": "fizzypop123",
    "Soccer Fan": "soccerfanatic",
    "Travel Bug": "traveltheworld",
    "Music Man": "musicmaniac",
    "Fitness Freak": "fitfreak23",
    "Pizza Lover": "pizzalover4eva",
    "Book Worm": "bookwormy",
    "Yoga Queen": "yogamastermind",
    "Foodie": "foodielove",
    "Gamer Girl": "gamergirl94",
    "Olivia Davis": "oliviadavis",
    "William Johnson": "williamjohnson",
    "Sophia Rodriguez": "sophiarodriguez",
    "Benjamin Wright": "benjaminwright",
    "Ava Mitchell": "avamitchell",
    "Maxwell Green": "maxwellgreen",
    "Evelyn Carter": "evelyncarter",
    "Gabriel Brown": "gabrielbrown",
    "Hannah Lee": "hannahlee",
    "Alexis White": "alexiswhite",
    "Jacob Taylor": "jacobtaylor",
    "Lauren Scott": "laurenscott",
    "Elijah Clark": "elijahclark",
    "Aaliyah Adams": "aaliyahadams",
    "Noah Baker": "noahbaker",
    "Chloe Hill": "chloehill",
    "Cameron Turner": "cameronturner",
    "Elizabeth Cooper": "elizabethcooper",
    "Anthony Perez": "anthonyperez",
    "Natalie Wood": "nataliewood",
    "James Foster": "jamesfoster",
    "Grace Rodriguez": "gracerodriguez",
    "Joshua King": "joshuaking",
    "Addison Hall": "addisonhall",
    "Christopher Wright": "christopherwright",
    "Madison Lopez": "madisonlopez",
    "Isaac Martinez": "isaacmartinez",
    "Avery Brown": "averybrown",
    "Hailey Parker": "haileyparker",
    "Jackson Bell": "jacksonbell",
    "Victoria Ramirez": "victoriaramirez",
    "Andrew Cooper": "andrewcooper",
    "Riley Nelson": "rileynelson",
    "Samuel Lee": "samuelle",
    "Leah Scott": "leahscott",
    "Logan Anderson": "logananderson",
    "Audrey Baker": "audreybaker",
    "Caleb Evans": "calebevans",
    "Claire Rivera": "clairerivera",
    "Luke Turner": "luketurner",
    "Sofia Collins": "sofiacollins",
    "Ethan Ross": "ethanross",
    "Ariana Mitchell": "arianamitchell",
    "Mason Hernandez": "masonhernandez",
    "Maria Phillips": "mariaphillips",
    "Dylan Peterson": "dylanpeterson",
    "Caroline Morris": "carolinemorris",
    "David Nguyen": "davidnguyen",
    "Aubrey Reyes": "aubreyreyes",
    "Isaiah Rivera": "isaiahrivera",
    "Peyton Davis": "peytondavis",
    "Levi Flores": "leviflores",
    "Abigail Stewart": "abigailstewart",
    "Nicholas Johnson": "nicholasjohnson",
    "Evelyn Smith": "evelynsmith",
    "Nathan Cooper": "nathancooper",
    "Emma Rogers": "emmarogers",
    "Anthony Lee": "anthoneylee",
    "Violet Diaz": "violetdiaz",
    "Tyler James": "tylerjames",
    "Harper Martinez": "harpermartinez",
    "Samuel Hill": "samuelhill",
    "Lucy Gonzalez": "lucygonzalez",
    "Christian Kelly": "christiankelly",
    "Audrey Perez": "audreyperez",
    "Josephine Turner": "josephineturner",
    "Owen Rodriguez": "owenrodriguez",
    "Stella Walker": "stellawalker",
    "Adrian Torres": "adriantorres",
    "Clara Sanchez": "clarasanchez",
    "Eli Thompson": "elithompson",
    "Leah Stewart": "leahstewart",
    "Luke Wright": "lukewright",
    "Emilia Ortiz": "emiliaortiz",
    "Thomas Green": "thomasgreen",
    "Avery Carter": "averycarter",
    "Ruby Hernandez": "rubyhernandez",
    "Sebastian Kim": "sebastiankim",
    "Sophie Collins": "sophiecollins",
    "Zachary Davis": "zacharydavis",
    "Lila Baker": "lilabaker",
    "Carter Wilson": "carterwilson",
    "Hazel Allen": "hazelallen",
    "Gavin Gonzalez": "gavingonzalez",
    "Avery Garcia": "averygarcia",
    "Eliana Adams": "elianaadams",
    "Julian Foster": "julianfoster",
    "Ivy Powell": "ivypowell",
    "Jeremiah Hill": "jeremiahhill",
    "Eleanor Collins": "eleanorcollins",
    "Aaron Wright": "aaronwright",
    "Katherine Flores": "katherineflores",
    "Adam Thomas": "adamthomas",
    "Mariah Smith": "mariahsmith",
    "Nicholas Allen": "nicholasallen",
    "Grace Kim": "gracekim",
    "Gabriel Martin": "gabrielmartin",
    "Jasmine Jones": "jasminejones",
    "Jack Lee": "jacklee",
    "Samantha Rodriguez": "samantharodriguez",
    "Jaxon Wright": "jaxonwright",
    "Alyssa Perez": "alyssaperez",
    "David Martin": "davidmartin",
    "Natalie Anderson": "natalieanderson",
    "Liam Turner": "liamturner",
    "Makayla Lewis": "makaylalewis",
    "Maxwell Scott": "maxwellscott",
    "Liliana Green": "lilianagreen",
    "Christopher Hill": "christopherhill",
    "Eva Rodriguez": "evarodriguez",
    "Cameron Stewart": "cameronstewart",
    "Landon Martinez": "landonmartinez",
    "Isabelle Reed": "isabellereed",
    "Jayden Wright": "jaydenwright",
    "Sofia Carter": "sofiacarter",
    "Parker Adams": "parkeradams",
    "Arianna Bailey": "ariannabailey",
    "Jace Harris": "jaceharris",
    "Charlotte King": "charlotteking",
    "William Turner": "williamturner",
    "Victoria Carter": "victoriacarter",
    "Ethan Evans": "ethanevans",
    "Maya Wilson": "mayawilson",
    "Landon Powell": "landonpowell",
    "Lila Foster": "lilafoster",
    "Jayden Kelly": "jaydenkelly",
    "Scarlett Turner": "scarlettturner",
    "Dominic Turner": "dominicturner",
    "Aaliyah Brown": "aaliyahbrown",
    "Grayson Adams": "graysonadams",
    "Aubrey Collins": "aubreycollins",
    "Aaron Hill": "aaronhill",
    "Ellie Ramirez": "ellieramirez",
    "Tristan Ross": "tristanross",
    "Avery Evans": "averyevans",
    "Gianna Foster": "giannafoster",
    "Blake Mitchell": "blakemitchell",
    "Aubree Scott": "aubreescott",
    "Xavier Kim": "xavierkim",
    "Sophia Morris": "sophiamorris",
    "Jaxson Lee": "jaxsonlee",
    "Madelyn Martin": "madelynmartin",
    "Isaac Robinson": "isaacrobinson",
    "Rylee Hernandez": "ryleehernandez",
    "Gabriel Lewis": "gabriellewis",
    "Aria Perez": "ariaperez",
    "Xander Martinez": "xandermartinez",
    "Mila Perez": "milaperez",
    "Zoe Wilson": "zoewilson",
    "Emmett Jones": "emmettjones",
    "Kaylee Davis": "kayleedavis",
    "Anthony Reed": "anthonyreed",
    "Delilah Turner": "delilahturner",
    "Josiah Parker": "josiahparker",
    "Naomi Kim": "naomikim",
    "Jason Wright": "jasonwright",
    "Nova Allen": "novaallen",
    "Caleb Flores": "calebflores",
    "Vivian Wright": "vivianwright",
    "Jaxson Powell": "jaxsonpowell",
    "Brooke Foster": "brookefoster",
    "Elijah Adams": "elijahadams",
    "Eva Lee": "evalee",
    "Leo Scott": "leoscott",
    "Elena Davis": "elenadavis",
    "Parker Turner": "parkerturner",
    "Addison Ramirez": "addisonramirez",
    "Colin Hill": "colinhill",
    "Christian Carter": "christiancarter",
    "Adalyn Flores": "adalyndlores",
    "Micah Powell": "micahpowell",
    "Luna Kim": "lunakim",
    "Graham Wright": "grahamwright",
    "Nina Evans": "ninaevans",
    "Jaxon Parker": "jaxonparker",
    "Ivy Davis": "ivydavis",
    "Easton Hill": "eastonhill",
    "Mariah Collins": "mariahcollins",
    "Ezekiel Turner": "ezekielturner",
    "Lilah Hernandez": "lilahhernandez",
    "Giovanni Scott": "giovanniscott",
    "Leah Mitchell": "leahmitchell",
    "Bentley Martin": "bentleymartin",
    "Maddison Wilson": "maddisonwilson",
    "Mason Ross": "masonross",
    "Adalynn Reed": "adalynnreed",
    "Emilia Perez": "emiliaperez",
    "Brayden Hernandez": "braydenhernandez",
    "Cora Adams": "coraadams",
    "Bryce Rodriguez": "brycerodriguez",
    "Eliza Turner": "elizaturner",
    "Asher Wright": "asherwright",
    "Hazel Lee": "hazellee",
    "Eliana Carter": "elianacarter",
    "Landon Davis": "landondavis",
    "Serenity Robinson": "serenityrobinson",
    "Knox Powell": "knoxpowell",
    "Natalie Hill": "nataliehill",
    "Emery Foster": "emeryfoster",
    "Elliott Kelly": "elliottkelly",
    "Makenna Turner": "makennaturner",
    "Connor Adams": "connoradams",
    "Adeline Jones": "adelinejones",
    "Logan Wright": "loganwright",
    "Juliana Mitchell": "julianamitchell",
    "Everett Scott": "everettscott",
    "Evelyn Ross": "evelynross",
    "Zane Hernandez": "zanehernandez",
    "Paige Martin": "paigemartin",
    "Emiliano Davis": "emilianodavis",
    "Raelynn Carter": "raelynncarter",
    "Jayce Flores": "jayceflores",
    "Miriam Robinson": "miriamrobinson",
    "Braylen Powell": "braylenpowell",
    "Alessandra Wright": "alessandrawright",
    "Caiden Hill": "caidenhill",
    "Luciana Lee": "lucianalee",
    "Enzo Adams": "enzoadams",
    "Khloe Perez": "khloeperez",
    "Jayceon Turner": "jayceonturner",
    "Talia Kim": "taliakim",
    "Gunner Wright": "gunnerwright",
    "Elianna Scott": "eliannascott",
    "Brooks Foster": "brooksfoster",
    "Aiyana Rodriguez": "aiyanarodriguez",
    "Marshall Wilson": "marshallwilson",
    "Jolene Hernandez": "jolenehernandez",
    "Derek Powell": "derekpowell",
    "Savannah Adams": "savannahadams",
}